name: Front Docker Image Build
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  FrontImageBuild:
    name: Build 2024-ac-hacking-front Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: walnuts1018
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2.5.0
        with:
          version: latest

      - name: Build and push Docker images
        uses: docker/build-push-action@v4.0.0
        with:
          push: true
          context: ./front
          platforms: linux/amd64
          tags: |
            ghcr.io/walnuts1018/2024-ac-hacking-front:latest
            ghcr.io/walnuts1018/2024-ac-hacking-front:${{ github.sha }}-${{ github.run_number }}
